name: Rewrite Rescates de Hoy

description: Ejecuta el script de backend para actualizar el archivo 'Rescates de hoy T-Habil.xlsx' en Google Drive usando los datos del archivo más reciente.

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear archivos OAuth (decodificar base64)
        run: |
          echo "${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET_B64 }}" | base64 -d > client_secret.json
          echo "${{ secrets.GOOGLE_OAUTH_TOKEN_B64 }}" | base64 -d > token.json

      - name: Ejecutar rewrite_rescates_de_hoy.py
        run: python rewrite_rescates_de_hoy.py
        env:
          GOOGLE_OAUTH_CLIENT_SECRET: client_secret.json
          GOOGLE_OAUTH_TOKEN: token.json